tags:
- name: Users
  description: Users API

paths:
  /users/{email}:
    get:
      tags:
      - Users
      summary: Find User By email
      parameters:
      - name: email
        in: path
        description: User id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

schemes:
 - https
 - http
